"""Invites

Revision ID: 243d3039806
Revises: af4790ce01
Create Date: 2013-01-29 19:31:54.117217

"""

# revision identifiers, used by Alembic.
revision = '243d3039806'
down_revision = 'af4790ce01'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invites',
    sa.Column('page_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=40), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], ),
    sa.PrimaryKeyConstraint('page_id', 'email')
    )

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###

    op.drop_table('invites')
    ### end Alembic commands ###
