"""Added Page

Revision ID: af4790ce01
Revises: 3441db8b467
Create Date: 2012-12-02 20:52:55.191209

"""

# revision identifiers, used by Alembic

revision = 'af4790ce01'
down_revision = '3441db8b467'

from alembic import op
import sqlalchemy as sa
import transaction
from demain.models import *


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('page_authorizations',
    sa.Column('page_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint()
    )
    op.add_column('tasks', sa.Column('page_id', sa.Integer(), nullable=False, server_default='1'))
#    ### end Alembic commands ###
    DBSession.configure(bind=op.get_bind())
    with transaction.manager:
        page = Page(name='default page')
        DBSession.add(page)
        page.users = DBSession.query(User).all()
        for task in DBSession.query(Task):
            task.page = page


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'page_id')
    op.drop_table('page_authorizations')
    op.drop_table('pages')
    ### end Alembic commands ###
